### ISSUE TITLE
Possibility to order by more than one field

### ISSUE THREAD

**Issue by toburger** [slaveOftime/Fun.OData#21]
Currently it is not possible to order by more than one field.

> Hint: the `query` computation expression defines a `thenBy` and `thenByDesc` operator for that scenarios (https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/query-expressions#table-1-query-operators).

**Comment by albertwoo** [comment]
You can just write things like:

```fsharp
odata<Contact> {
    orderBy (fun x -> x.Phone)
    orderByDesc (fun x -> x.Email)
}
```

And it will generate things like:
```txt
"$select=Phone,Email&$orderby=Phone,Email desc"
```

**Comment by toburger** [comment]
Ah, thanks, I didn't realize that this works!
